name: 'Setup Terraform'
description: 'Setup Terraform with caching and authentication'

inputs:
  terraform_version:
    description: 'Terraform version'
    required: false
    default: '1.7.0'
  cloud:
    description: 'Cloud provider (aws/azure/gcp)'
    required: true
  environment:
    description: 'Target environment (dev/stg/prd)'
    required: true
  tfc_token:
    description: 'Terraform Cloud API token'
    required: false
    default: ''

outputs:
  terraform_version:
    description: 'Installed Terraform version'
    value: ${{ steps.setup.outputs.terraform_version }}

runs:
  using: 'composite'
  steps:
    - name: Setup Terraform
      id: setup
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ inputs.terraform_version }}
        cli_config_credentials_token: ${{ inputs.tfc_token }}

    - name: Configure AWS Credentials
      if: inputs.cloud == 'aws'
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ vars[format('AWS_ROLE_ARN_{0}', inputs.environment)] }}
        aws-region: ap-northeast-1

    - name: Configure Azure Credentials
      if: inputs.cloud == 'azure'
      uses: azure/login@v2
      with:
        client-id: ${{ vars.AZURE_CLIENT_ID }}
        tenant-id: ${{ vars.AZURE_TENANT_ID }}
        subscription-id: ${{ vars[format('AZURE_SUBSCRIPTION_ID_{0}', inputs.environment)] }}

    - name: Configure GCP Credentials
      if: inputs.cloud == 'gcp'
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: ${{ vars.GCP_WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ vars[format('GCP_SERVICE_ACCOUNT_{0}', inputs.environment)] }}

    - name: Terraform Version
      shell: bash
      run: terraform version
